@baseUrl = http://localhost:3000
@userId = 8ab3f5bc-a5be-4109-9e19-a2d2b5d2ef76
@equipoId = c6c26864-b819-449f-9373-dce846cfceb3

@tareaId = 511d3187-7c8d-4ad0-a854-b30994f4c73b

@user2Id = 76a71a0d-6fa4-421f-9ffd-98bcb6634430

@commentId = 8f3b2c1a-3e4d-4f5a-9c6d-7e8f9a0b1c2d

###
### Swagger UI
GET {{baseUrl}}/docs


### Estado del sistema
GET {{baseUrl}}/api/status


### ---------- Usuarios ----------

### Registrar usuario
POST {{baseUrl}}/api/users/register
Content-Type: application/json

{
  "nombre": "Ezequiel2",
  "email": "eze4@example.com.ar",
  "password": "123456"
}


### Login
POST {{baseUrl}}/api/users/login
Content-Type: application/json

{
  "email": "eze4@example.com.ar",
  "password": "123456"
}


### Actualizar usuario
PUT {{baseUrl}}/api/users/{{userId}}
Content-Type: application/json

{
  "nombre": "EzequielPepe",
  "email": "eze4@example.com.ar",
  "password": "123456"
}



### Borrar usuario
DELETE {{baseUrl}}/api/users/{{userId}}
Content-Type: application/json

{
  "id": "{{userId}}"
}


### ---------- Equipos ----------

### Salir del equipo
POST {{baseUrl}}/api/equipos/{{equipoId}}/salir
Content-Type: application/json

{
  "userId": "{{user2Id}}"
}


### Obtener Equipos
GET {{baseUrl}}/api/equipos/{{userId}}/listar
Content-Type: application/json

{
  "userId": "{{userId}}"
}


### Crear equipo
POST {{baseUrl}}/api/equipos/{{userId}}
Content-Type: application/json

{
  "nombre": "Equipo Backend",
  "propietarioId": "{{userId}}"
}





### Invitar miembro al equipo
POST {{baseUrl}}/api/equipos/{{equipoId}}/invitar
Content-Type: application/json

{
  "usuarioId": "{{user2Id}}",
  "propietarioId": "{{userId}}"
}

### Borrar equipo

DELETE {{baseUrl}}/api/equipos/{{equipoId}}
Content-Type: application/json

{
  "userId": "{{userId}}"
}


### ---------- Tareas ----------



### Listar tareas por filtro
GET {{baseUrl}}/api/tareas/{{equipoId}}
Content-Type: application/json

{
  "equipoId": "{{equipoId}}",
  "prioridad": "Alta",
  "estado": "Pendiente"
}



### Crear tarea
POST {{baseUrl}}/api/tareas
Content-Type: application/json

{
  "titulo": "Implementar login",
  "descripcion": "Crear endpoint de login con JWT",
  "creadorId": "{{userId}}",
  "equipoId": "{{equipoId}}",
  "prioridad": "Alta",
  "estado": "Pendiente"
}



### Cambiar estado de tarea
PUT {{baseUrl}}/api/tareas/{{tareaId}}/estado
Content-Type: application/json

{
  "nuevoEstado": "En curso",
  "usuarioId": "{{userId}}"
}

### Eliminar tarea
DELETE {{baseUrl}}/api/tareas/{{tareaId}}/{{userId}}
Content-Type: application/json

{
  "tareaId": "{{tareaId}}",
  "usuarioId": "{{userId}}"
}

### ---------- Comentarios ----------

### Listar comentarios de una tarea
GET {{baseUrl}}/api/comentarios/tareas/{{tareaId}}/comentarios
Content-Type: application/json

{
  "tareaId": "{{tareaId}}"
}

### Crear comentario en una tarea
POST {{baseUrl}}/api/comentarios/tareas/{{tareaId}}/comentarios
Content-Type: application/json

{
  "contenido": "Este es un comentario de prueba.",
  "autorId": "{{userId}}"
}

### Editar comentario
PUT {{baseUrl}}/api/comentarios/{{commentId}}
Content-Type: application/json

{
  "contenido": "Comentario editado."
}

### Eliminar comentario
DELETE {{baseUrl}}/api/comentarios/{{commentId}}
Content-Type: application/json

{
  "id": "{{commentId}}"
}