@baseUrl = http://localhost:3000
@userId = d4d16a5f-fc0d-4c1b-8f88-c73f37523b63
@equipoId = e3295e73-af49-4a01-a93c-b1b8c30dcbab

@tareaId = 5c9daba3-1006-42b9-b9b5-cd574feb4c1c

###
### Swagger UI
GET {{baseUrl}}/docs


### Estado del sistema
GET {{baseUrl}}/api/status


### ---------- Usuarios ----------

### Registrar usuario
POST {{baseUrl}}/api/users/register
Content-Type: application/json

{
  "nombre": "Ezequiel1",
  "email": "eze3@example.com.ar",
  "password": "123456"
}


### Login
POST {{baseUrl}}/api/users/login
Content-Type: application/json

{
  "email": "eze3@example.com.ar",
  "password": "123456"
}


### Actualizar usuario
PUT {{baseUrl}}/api/users/{{userId}}
Content-Type: application/json

{
  "nombre": "EzequielPepe",
  "email": "eze3@example.com.ar",
  "password": "123456"
}



### Borrar usuario
DELETE {{baseUrl}}/api/users/{{userId}}
Content-Type: application/json

{
  "id": "{{userId}}"
}


### ---------- Equipos ----------

### Obtener Equipos
GET {{baseUrl}}/api/{{userId}}


### Crear equipo
POST {{baseUrl}}/api/equipos/{{userId}}
Content-Type: application/json

{
  "nombre": "Equipo Backend",
  "propietarioId": "{{userId}}"
}


### Invitar miembro al equipo
POST {{baseUrl}}/api/equipos/{{equipoId}}/invitar
Content-Type: application/json

{
  "usuarioId": "4ee15231-e249-43e7-a734-262347ee1292",
  "propietarioId": "{{userId}}"
}

### Salir del equipo
POST {{baseUrl}}/api/{{userId}}/salir
Content-Type: application/json

{
  "equipoId": "{{equipoId}}"
}

DELETE {{baseUrl}}/api/equipos/{{userId}}
Content-Type: application/json

{
  "equipoId": "{{equipoId}}"
} 

### ---------- Tareas ----------

### Listar tareas por equipo
GET {{baseUrl}}/api/tareas/equipo/{{equipoId}}
Content-Type: application/json

{
  "equipoId": "{{equipoId}}"
}

### Crear tarea
POST {{baseUrl}}/api/tareas
Content-Type: application/json

{
  "titulo": "Implementar login",
  "descripcion": "Crear endpoint de login con JWT",
  "creadorId": "{{userId}}",
  "equipoId": "{{equipoId}}",
  "prioridad": "Alta",
  "estado": "Pendiente"
}



### Cambiar estado de tarea
PUT {{baseUrl}}/api/tareas/{{tareaId}}/estado
Content-Type: application/json

{
  "nuevoEstado": "En curso",
  "usuarioId": "{{userId}}"
}

### Eliminar tarea
DELETE {{baseUrl}}/api/tareas/{{tareaId}}/{{userId}}
Content-Type: application/json

{
  "tareaId": "{{tareaId}}",
  "usuarioId": "{{userId}}"
}